apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: payment-api
        image: 557809209084.dkr.ecr.eu-north-1.amazonaws.com/payment-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: db-pass
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
